name = "ThreadedSparseCSR"
uuid = "39591389-4884-462a-89e7-9edfce40b6eb"
authors = ["Bruno Amorim <amorim.bac@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
